# spring.mvc.view.prefix=/WEB-INF/jsp/
# spring.mvc.view.suffix=.jsp
#spring.mvc.static-path-pattern,

spring:
   mvc:
      static-path-pattern: /static/**
      view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/honftel?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: root
